name: Simple CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print success message
        run: echo "Hello Shaikh, your first CI pipeline is running successfully!"